package com.weight.miaotu.bean.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.widget.miaotu.http.bean.SeedlingInfo;

import com.weight.miaotu.bean.greendao.SeedlingInfoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig seedlingInfoDaoConfig;

    private final SeedlingInfoDao seedlingInfoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        seedlingInfoDaoConfig = daoConfigMap.get(SeedlingInfoDao.class).clone();
        seedlingInfoDaoConfig.initIdentityScope(type);

        seedlingInfoDao = new SeedlingInfoDao(seedlingInfoDaoConfig, this);

        registerDao(SeedlingInfo.class, seedlingInfoDao);
    }
    
    public void clear() {
        seedlingInfoDaoConfig.clearIdentityScope();
    }

    public SeedlingInfoDao getSeedlingInfoDao() {
        return seedlingInfoDao;
    }

}
